<?php
$cfg=Array(
'doc_title'=>'New Page',
'footer'=>'&copy; New Page',
'meta_d'=>'',
'meta_k'=>'',
'gmenu'=>'<a href="index.php?d=1">Nowo¶ci</a> | <a href="?co=cats">Artyku³y</a> | <a href="?co=cats&amp;id=2">Pliki</a>',
'dkh'=>'',
'robots'=>'all',
'c'=>'ZMIEN_TO',
'cms_styl'=>'continuous',
'num'=>1,
'mc'=>1,
'fdate'=>'Dzisiaj jest: %d.%m.%y.',
'fdate1'=>'%d.%m.%y',
'fdate2'=>' o %h:%i',
'lastv'=>1,
'reg_on'=>1,
'pms_on'=>1,
'pm_limit'=>20,
'ufind'=>1,
'lng'=>1,
'ban'=>'',
'cnp'=>15,
'gcomm'=>1,
'bbc'=>1,
'coml'=>30,
'csort'=>2,
'pcomm'=>1,
'cproc'=>0,
'pollr1'=>'standard',
'pollr2'=>'standard',
); ?>